name: "ITPP Runbot: Install"

on:
  push:
    paths:
      - ".itpp-runbot/config.yml"

jobs:
  upload-files:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      path: repo
    - name: Get Runbot Version
      run: |
        ITPP_RUNBOT_VERSION="$(cat repo/config.yaml | grep itpp-runbot-version | awk '{print $NF}')"
        # use master by default
        ITPP_RUNBOT_VERSION="${ITPP_RUNBOT_VERSION:-master}"
        # see https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions
        echo "::set-env name=ITPP_RUNBOT_VERSION::$ITPP_RUNBOT_VERSION"
    - name: Checkout ITPP-Runbot
      uses: actions/checkout@v1
      path: itpp-runbot
      ref: ${{ env.ITPP_RUNBOT_VERSION }}
    - name: Check for initial upload editable files
      run: |
        cp -rnT itpp-runbot/editable-files/ repo/
    - name: Update Docker Workflow
      run: |
        SCHEDULE_CRON="$(cat repo/config.yaml | grep image-rebuilding-schedule | awk -F\" '{print $2}')"
        cp itpp-runbot/workflows/itpp-runbot.yml repo/.github/workflows/
        sed -i "s/SCHEDULE_CRON/$SCHEDULE_CRON/" repo/.github/workflows/itpp-runbot.yml
    - name: Commit changes
      uses: EndBug/add-and-commit@v2.1.1
      with:
        author_name: Marc Demo (Github Actions)
        author_email: i18n-bot@it-projects.info
        message: ":alien: Update ITPP Runbot files"
        path: "repo"
        pattern: "*"
        force: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify Github App
      run: |
        [[ "$NOTIFY_APP" = "yes" ]] && echo "TODO curl request"
